### PR TITLE
add plans

### PR DESCRIPTION
**Pull request by s-hackman**
added initial plan image

### CODE REVIEW

**Review by NRMSMITH — COMMENTED** [review]
How about an empty path? I know you're emulating reddit, but shouldn't there be a general home page and then you can either click on articles or list the articles? You can't guarantee that someone won't just type in 'www.notReddit.com'.

**Comment by s-hackman** [comment]
good point I will add a homepage aswell for default path

**Comment by NRMSMITH** [comment]
Go through all the endpoints in your backend and have a look on how they will look in your frontend :)

**Review by NRMSMITH — APPROVED** [review]
👍 good to go! 🚀 Well done!

**Pull request merged**
